spring:
  application:
    name: figure-preorder-ledger-backend
  profiles:
    default: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: ${app.upload.max-size}
      max-request-size: ${app.upload.max-size}
  web:
    locale: ko_KR
    locale-resolver: fixed

app:
  upload:
    max-size: 5MB
    allowed-extensions: [jpg, jpeg, png, gif, webp]

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jong.figurepreorderledgerbackend.vo
  configuration:
    map-underscore-to-camel-case: true
